import './globals.css';
import type { Metadata } from 'next';
import { Inter, Noto_Sans_KR } from 'next/font/google';
import {} from 'next/font/google';
import Nav from '@/components/Nav';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

const notoSansKr = Noto_Sans_KR({
  // preload: true, 기본값
  subsets: ['latin'], // 또는 preload: false
  weight: ['100', '400', '700', '900'], // 가변 폰트가 아닌 경우, 사용할 fontWeight 배열
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <Head>
        <meta charSet="utf-8" />
      </Head>
      <body className={`font-display bg-white px-4 mx-auto max-w-[640px]`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
